ajemoskowitz/thus-tours

- app/controllers/bookings_controller.rb
- app/controllers/tours_controller.rb
> added edit and update functions. please peer review.

- app/controllers/application_controller.rb
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
added name field to sign-up form
put containers around the forms to give them some margins in the page
> login is styled and sign-up asks for name

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/pages/_show.scss
- app/views/tours/show.html.erb
The request form will be add when the booking controller is complete.
> create show page skeleton design

- app/controllers/bookings_controller.rb
> Completed BookingsController

- app/policies/booking_policy.rb
- test/policies/booking_policy_test.rb
please don't work on bookings controller for now
> initialized bookings auths

- app/policies/booking_policy.rb
let's merge this to see if we can test the 'create bookings' form
> untested booking authorizations

- app/controllers/bookings_controller.rb
- app/controllers/tours_controller.rb
- app/views/tours/show.html.erb
> bookings form works on tour show page

- db/seeds.rb
made edits so the tour name is capitalized
> Edited seeds.

- app/controllers/bookings_controller.rb
- app/views/bookings/index.html.erb
made a couple rails mistakes in the bookings controller and with the booking_path in the bookings index
> fixed bug that prevented bookings from being cancelled

- app/assets/stylesheets/application.scss
- app/controllers/providers/bookings_controller.rb
- app/controllers/providers/tours_controller.rb
- app/views/layouts/application.html.erb
if user has created tours, a tour manager dropdown appears in the navbar 
also started working on the providers controllers
> Providers manager on toolbar

- app/views/bookings/index.html.erb
> a user's booking index separates confirmed tours from unconfirmed ones

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_map.scss
- app/controllers/tours_controller.rb
- app/javascript/packs/application.js
- app/javascript/plugins/init_autocomplete.js
- app/javascript/plugins/init_mapbox.js
- app/models/tour.rb
- app/views/tours/_infowindow.html.erb
- app/views/tours/index.html.erb
- config/initializers/geocoder.rb
- package.json
- yarn.lock
will add style to the map later
> add working map to index page

- app/assets/stylesheets/pages/_bookings.scss
- app/views/bookings/index.html.erb
change cancel button location and style, adjust margins and change info text style
> change cancel button location and style and adjust margins

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/pages/_providers_bookings.scss
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/providers/bookings/index.html.erb
> provider bookings page

- app/controllers/users_controller.rb
- app/javascript/components/x_button.js
- app/policies/user_policy.rb
- app/views/shared/_navbar.html.erb
- app/views/users/show.html.erb
- config/routes.rb
- test/controllers/users_controller_test.rb
- test/policies/user_policy_test.rb
most of these files were generated to create user profile pages
there's a javascript file that you can ignore for now
> User profile

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/pages/_bookings.scss
- app/views/bookings/index.html.erb
bookings page make tab for pending and confirmed section
> bookings page

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/pages/_providers_tours.scss
- app/views/providers/tours/index.html.erb
add provider tours page with edit and delete btn
Edit function work
Delete function broken when it return
> provider tours page

- app/assets/stylesheets/pages/_providers_tours.scss
- app/views/providers/tours/index.html.erb
providers bookings changed d-flex to grid columns
> provider booking pg fixed

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/pages/_providers_bookings.scss
- app/assets/stylesheets/pages/_providers_tours.scss
- app/views/providers/bookings/index.html.erb
make navbar drop down menu text darker
> navbar-dropdown-dark-text

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/pages/_providers_tours.scss
application.scss : make dropdwon text darker
provider_tours.scss: changing ul that not effect on provider bookings list
> fixing provider booking list

- app/assets/stylesheets/pages/_providers_tours.scss
- app/views/providers/tours/index.html.erb
changing ul name for provider card, (solve conflict name with tour index page)
> changing ul name for provider card
